### ISSUE TITLE
Does AmazonIVSPlayer support for static xcframework?

### ISSUE THREAD

**Issue by dwirandytlvk** [aws-samples/amazon-ivs-player-ios-sample#26]
Hallo there
Does AmazonIVSPlayer support for static xcframework?

**Describe the bug**
As i know it would be great to support static xcframework to decrease my app launch screen

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device details (please complete the following information):**

**Additional context**

**Comment by dwirandyh** [comment]
cc: @CFKevinRef @ryanecrist

**Comment by dwirandytlvk** [comment]
cc: @ryanecrist @CFKevinRef

**Comment by CFKevinRef** [comment]
We don't have any current plans to release a static XCFramework. Also, static linking is not necessarily the best way to decrease your app's startup time.

First I recommend taking all the steps in Apple's official guide, [Reducing Your App’s Launch Time](https://developer.apple.com/documentation/xcode/reducing-your-app-s-launch-time) and the related WWDC video, [Optimizing App Launch](https://developer.apple.com/videos/play/wwdc2019/423/). Specifically make sure you have profiled and identified that dyld loading is actually a significant contributor!

Statically linking dependencies can improve startup time to a point, but it's actually even faster to use dynamic frameworks _loaded at runtime as needed_. That way dependencies don't impact startup time at all, because they're not linked even statically. This is an advanced technique (often referred to as a "Plugin-based" architecture) using the [`Bundle`](https://developer.apple.com/documentation/foundation/bundle) and/or `dlopen()` APIs. This is also far beyond the scope of this video player library, but hopefully it offers some good starting points for further research.
