### ISSUE TITLE
Player Freeze Issue

### ISSUE THREAD

**Issue by DineshkumarKandasamy** [aws-samples/amazon-ivs-player-ios-sample#46]
Hi @ryanecrist Player is getting freeze in Two cases:
Case 1: While app goes background and comes foreground player plays for some time and freezes
Case 2: If we left the mobile by playing the stream for more than 30 mins it freezes

Also some times sound not audible and video only playing. Some times black screen comes and audio only playing.

This issue not occurs for some times if we delete the app and re-install. Kindly give your feedbacks

Can we get the player log's from the Test flight released build? We could not able to reproduce the issue, while we try to run the app in local. Kindly suggest

I have added log files for your reference. Kindly check [Download speed was 88mbps/s while testing]

[Log1.txt](https://github.com/aws-samples/amazon-ivs-player-ios-sample/files/11180494/Log1.txt)

[log2.txt](https://github.com/aws-samples/amazon-ivs-player-ios-sample/files/11180495/log2.txt)

[log3.txt](https://github.com/aws-samples/amazon-ivs-player-ios-sample/files/11180497/log3.txt)

**Comment by DineshkumarKandasamy** [comment]
Hi @ryanecrist Could you please check this issue as a high priority? We have important release in this week. It will be more help full if we get your support on this. Thanks in advance.

**Comment by ryanecrist** [comment]
Hi @DineshkumarKandasamy, thanks for filing an issue. In order to help us investigate, can you provide the following?

1. A minimal example that reproduces the specific issue you're seeing.
2. What specifically happens when the player "freezes"? (i.e. does it enter the idle state, is the main thread "stuck" in your app, etc.).
3. Any other details that you think might help our team reproduce the issue would be greatly appreciated.

> Can we get the player log's from the Test flight released build? We could not able to reproduce the issue, while we try to run the app in local. Kindly suggest

Unfortunately I don't think it's possible to obtain the device logs via Test Flight. If you have access to the impacted device(s) you can collect them via the Console app on your mac (or perhaps request a Test Flight user to do this on your behalf).

> Hi @ryanecrist Could you please check this issue as a high priority? We have important release in this week. It will be more help full if we get your support on this. Thanks in advance.

If urgent troubleshooting or technical support is needed, please reach out to AWS Support via the AWS Support Center (https://docs.aws.amazon.com/awssupport/latest/user/getting-started.html).

**Comment by DineshkumarKandasamy** [comment]
Hi @ryanecrist Thanks for the reply.

A minimal example that reproduces the specific issue you're seeing:
>Step 1: While app goes background and comes foreground player plays for some time and freezes
>Step 2: If we left the mobile by playing the stream for more than 30 mins it freezes

What specifically happens when the player "freezes"?
>Some time app is getting freezed.
>Some time black screen is displayed in the home page.
>Some time audio is not audible but video is playing
>Some time audio is playing but screen is freezed

Any other details that you think might help our team reproduce the issue would be greatly appreciated.
>I have added log's for your reference. These three logs were taken while the app freeze. Hope it will be useful for you to >track the issue.

**Comment by ryanecrist** [comment]
Hi @DineshkumarKandasamy,

Regarding the minimal example, we'd be looking for a code sample (i.e. a fork of this repo, for example) that demonstrates the issue you're seeing in a project that isn't your application. Thanks!
