### ISSUE TITLE
iOS - IVS Player - Automatically goes to idle state.

### ISSUE THREAD

**Issue by BalaSportsGravy** [aws-samples/amazon-ivs-player-ios-sample#70]
While playing the Live Stream, IVS player automatically goes to idle state. Its happening only on recent times. Any idea how to debug this or to find the root cause of this issue?. Stream was filmed using Amazon Broadcast iOS SDK.

**Comment by ryanecrist** [comment]
Hello, thanks for filing an issue.

In order to help us investigate, can you provide the following?
1. What version of the SDK are you using?
2. Is this issue observable on all iOS versions?
3. Is this issue happening with a particular stream or all streams? VODs vs livestream?
4. Is this issue happening when streaming via AWS IVS or another system?
5. Can you collect debug logs when this issue is observed? You can enable debug logging via the log level property on the player:
    ```swift
    let player = IVSPlayer()
    player.logLevel = .debug
    ```
6. Can you provide a minimal example to reproduce this issue? For example, using one of the demo apps in this repo?
7. Any other useful information you think will help in our investigation.

If urgent troubleshooting or technical support is needed, please reach out to AWS Support via the AWS Support Center (https://docs.aws.amazon.com/awssupport/latest/user/getting-started.html).

**Comment by BalaSportsGravy** [comment]
Hello, thanks for your reply,

I have attached my response below, please check.

1. What version of the SDK are you using? - **1.34.0**
2. Is this issue observable on all iOS versions? - Yes - **Current version is iOS 18**
3. Is this issue happening with a particular stream or all streams? VODs vs livestream? - **Particular Streams - Like if there is an intermission, so the stream will stitched together and play as an single file. VOD file**
4. Is this issue happening when streaming via AWS IVS or another system? - **AWS IVS**
5. Can you collect debug logs when this issue is observed? You can enable debug logging via the log level property on the player:
I am getting below error,
**AudioConverterDecoder error 1650549857 message AudioConverterFillComplexBuffer** in the debug log

**Comment by BalaSportsGravy** [comment]
@ryanecrist any update on above issue?

**Comment by ryanecrist** [comment]
Hi @BalaSportsGravy, this is not a customer support forum, so I encourage you to reach out to AWS Support for help with your issue.

That being said, the error code you observed in logs suggests that something is wrong with the audio codec of the stream: 
* [kAudioCodecBadDataError](https://developer.apple.com/documentation/audiotoolbox/1494076-audio_codec_errors/kaudiocodecbaddataerror)
* https://osstatus.com/search/results?platform=all&framework=all&search=1650549857

I recommend checking out our [low latency streaming user guide](https://docs.aws.amazon.com/ivs/latest/LowLatencyUserGuide/streaming-config.html) and comparing your setup to what's recommended: 
> Audio Settings
>We support the following settings:
>* Codec: AAC (LC)
>* Bitrate: 96 Kbps to 320 Kbps
>* Sample rate: 44.1 Khz or 48 Khz (it is best to match your production audio flow)
>* Channels: Maximum 2 - Stereo (1: mono or 2: stereo audio channel support)

**Comment by BalaSportsGravy** [comment]
Thanks for your reply, I will check and update on this.

**Comment by ryanecrist** [comment]
Closing this issue. Please re-open or file a new issue if you suspect a bug within the Amazon IVS Player SDK.
